name: awan
description: "Projek untuk mendapatkan segala info berkaitan pengangkutan awam di kawasan Lembah Klang"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  forui: ^0.4.0
  gap: ^3.0.1
  path_provider: ^2.1.4
  june: ^1.0.0+1
  flutter_hooks: ^0.20.5
  intl:
  drift: ^2.20.0
  drift_flutter: ^0.1.0
  dio: ^5.4.0
  archive: ^3.4.10
  csv: 6.0.0
  crypto: ^3.0.3
  collection: ^1.18.0
  roggle: ^0.4.2+1  # logging
  orange: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.20.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
