name: awan
description: "Projek untuk mendapatkan segala info berkaitan pengangkutan awam di kawasan Lembah Klang"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  # ui
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  forui: ^0.5.0
  gap: ^3.0.1
  go_router: ^14.2.7

  # fungsi umum
  archive: ^3.4.10
  collection: ^1.18.0
  crypto: ^3.0.3
  csv: 6.0.0
  dio: ^5.4.0
  june: ^1.0.0+1
  intl:
  path_provider: ^2.1.4
  roggle: ^0.4.2+1  # logging
  flutter_dotenv: ^5.1.0

  # database
  drift: ^2.20.0
  drift_flutter: ^0.1.0
  orange: ^1.2.8

  # peta
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  mapbox_maps_flutter: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.20.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/imej/
